### PR TITLE
Update generative_network.py

### PR DESCRIPTION
**Pull request by FrankFeenix**
### Summary
Just a little fix for a better performance.  Nothing more.

### CODE REVIEW

**Comment by adekusar-drl** [comment]
Could you please add a description to the PR: what the goal of this PR is and why the suggested code is better? If it is better, I would rather explore the code to replace other such places.

**Comment by FrankFeenix** [comment]
> Could you please add a description to the PR: what the goal of this PR is and why the suggested code is better? If it is better, I would rather explore the code to replace other such places.

Edited. Will be happy if the PR passed. Thanks

**Comment by adekusar-drl** [comment]
Could you please update this line as well?
https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/algorithms/distribution_learners/qgan/discriminative_network.py#L36

**Comment by FrankFeenix** [comment]
> Could you please update this line as well?
> https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/algorithms/distribution_learners/qgan/discriminative_network.py#L36

Done. I don't have time to test it all to make it smoother. It's like a slight modification of the above. Thank you

**Review by stefan-woerner — APPROVED** [review]
lgtm

**Review by woodsp-ibm — APPROVED** [review]

**Pull request merged**
