### PR TITLE
Add title images to the tutorials

### LINKED ISSUE #196: Add title images to the tutorials
### What is the expected enhancement?
Tutorials posted on the QML documentation page, https://qiskit.org/documentation/machine-learning/tutorials/index.html, may have a title image, e.g. the qGANs and Quantum Kernel tutorials have such images, while other tutorials do not. See the screenshot:
image

To make the page look better I suggest to add title images to other three tutorials:

- Quantum Neural Networks: to be decided/chosen.
- Neural Network Classifier & Regressor: a classification image.
- TorchConnector: likely an MNIST image should be good.

Images can be added by tagging a cell. A sphinx thumbnail tag in a tutorial cell that produces a figure must be set. If you enable View / Cell Toolbar / Tags you should see it in the above mentioned tutorials as an example.

### PR DESCRIPTION
**Pull request by YumaNK**
### Summary
Thumbnails of "Neural Network Classifier & Regressor" and "TorchConnector" are added.
Since I respect the notebook contents themselves, I did not change the notebooks except tags and did only used images in their notebooks.
As the thumbnail of "Quantum Neural Networks" is  to be decided/chosen, I remained untagged.
Closes #196.

### Details and comments

image

### CODE REVIEW

**Comment by YumaNK** [comment]
Fixed issue of  
https://github.com/Qiskit/qiskit-machine-learning/issues/196

**Review by adekusar-drl — COMMENTED** [review]
Thanks, looks good. Do you have any ideas what can be a title image in the first tutorial?
Let's wait for the CI checks to see if everything is good to go.

**Comment by YumaNK** [comment]
> Thanks, looks good. Do you have any ideas what can be a title image in the first tutorial?
> Let's wait for the CI checks to see if everything is good to go.

If I can add an image outside of jupyter output, I am wondering to choose an image from GGSS2021 lecture 8.1 by Francesco Tacchino. 
If you think ok, I will ask his permission to use the image.
image

**Comment by adekusar-drl** [comment]
> 
> If I can add an image outside of jupyter output, I am wondering to choose an image from GGSS2021 lecture 8.1 by Francesco Tacchino.
> If you think ok, I will ask his permission to use the image.

Thanks, I think we can leave it as it is now.

**Review by adekusar-drl — APPROVED** [review]

**Pull request merged**
