### PR TITLE
Rename var_form to ansatz

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

Deal with https://github.com/Qiskit/qiskit-terra/pull/6128
Fix lint issues of 'test/regressors' https://github.com/Qiskit/qiskit-machine-learning/pull/31#issuecomment-811779059

### CODE REVIEW

**Review by stefan-woerner — CHANGES_REQUESTED** [review]
Please also rename the variable form `var_form` to `ansatz`

**Comment by stefan-woerner** [comment]
and good catch, I don't understand how the test could actually pass?

**Comment by adekusar-drl** [comment]
@t-imamichi Could you please also:
- add `__init__.py` into `test/algorithms/regressors`. Without it the tests are not run by the CI.
- rename test methods in `TestNeuralNetworkRegressor` from `classifier` to `regressor`.

**Comment by t-imamichi** [comment]
Yes. I will fix these issues too.

**Comment by adekusar-drl** [comment]
@t-imamichi Thanks a lot!

**Review by stefan-woerner — APPROVED** [review]

**Pull request merged**
