### PR TITLE
Improved content for Tutorial 5 (QAMP fall'22)

### PR DESCRIPTION
**Pull request by SanyaNanda**
### Summary
Enhancing the documentation of Tutorial "05_torch_connector" as a mentee for QAMP 2022.
Mentor: @ElePT
Mentee: @SanyaNanda

### Details and comments
Restructured the notebook (Objective, Introduction, Tutorial and what was learned)
Imports placed where required
Added Detailed Explanations in all the sections
Inline comments for better understanding of the code and arguments used in function
Hyperlinks to API references wherever required

### CODE REVIEW

**Comment by adekusar-drl** [comment]
Thanks for taking care of this. The 05 tutorial was slightly changed. Could you please merge your work with the latest version of the tutorial? I can help if you have issues.

**Comment by SanyaNanda** [comment]
Thank you! I will do this and get in touch in case of queries

Issue with running of cells resolved. Problem in estimating regression accuracy.

**Comment by adekusar-drl** [comment]
> Problem in estimating regression accuracy.
What's the problem?

**Comment by SanyaNanda** [comment]
In cells 13,14: I added code for regression accuracy as it was missing, but I think the formula I am using is not correct. I was getting a format error, so I commented those particular lines out

**Comment by adekusar-drl** [comment]
> regressor_accuracy_score = sum(y_ == y) / len(y)

This is not a great metric for a regression problem. Perhaps it is close to zero. Take a look at root mean squared error (RMSE) or R2 metric. They are suitable for regression problems. Or explore: https://scikit-learn.org/stable/modules/model_evaluation.html

**Comment by SanyaNanda** [comment]
Yes I was getting the error as zero. I will checkout the link and incorporate changes accordingly. Thankyou!

**Comment by SanyaNanda** [comment]
New PR: https://github.com/Qiskit/qiskit-machine-learning/pull/534

**Pull request closed without merging**
