### PR TITLE
Grammar Fixes

### PR DESCRIPTION
**Pull request by AngeloDanducci**
### Summary
Fixes an issue in another repo that points to here https://github.com/Qiskit/qiskit/issues/1291

### Details and comments
A few grammar fixes in `01_neural_networks.ipynb`

### CODE REVIEW

**Comment by adekusar-drl** [comment]
@woodsp-ibm looks good to me. What do you think?

**Review by woodsp-ibm — APPROVED** [review]
It looks fine to me. Maybe we want to mark it as stable backport to get it over to stable - though perhaps we do not need from there to update/re-publish docs quite yet, since you have more updates to these notebooks coming?

**Comment by adekusar-drl** [comment]
For the minor update like this, I think, we can postpone documentation update.

**Comment by woodsp-ibm** [comment]
Ok it still could have been backported. We'll have to check when we do backport docs that the change done here is catered to so that we do not just backport changes done after this and perhaps miss this.

**Comment by adekusar-drl** [comment]
It is still can be backported.

**Pull request merged**
