### PR TITLE
Issue 175 | Fix zero dim shaped gradients for NeuralNetworks

### LINKED ISSUE #175: Torchconnector fails in backward prop
In the backward propagation this code checks `input_grad` and if _not_ None under certain a condition sets it to None

https://github.com/Qiskit/qiskit-machine-learning/blob/00831061ca0206af42e131fcb9b605c4acd404fa/qiskit_machine_learning/connectors/torch_connector.py#L158-L160

later in the same method it makes this call

https://github.com/Qiskit/qiskit-machine-learning/blob/00831061ca0206af42e131fcb9b605c4acd404fa/qiskit_machine_learning/connectors/torch_connector.py#L178

which fails inside Torch einsum util with a complaint about NoneType (which seems to be about input_grad being None)

Similar logic is in the `weight_grad` part too.

I will note that the above logic path, where input_grad is set to None, is not covered by unit tests and so this failure does not arise there.

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary
Neural networks (`CircuitQNN`) currently failing on backward prop when input parameters or weight parameters are empty.

### Details and comments

This is a quick fix to use additional check in `_validate_backward_output`. 

Closes #175

### CODE REVIEW

**Comment by IceKhan13** [comment]
Ideal option would be avoiding zero dim in shapes of gradients at all (a.k.a fallback earlier). This will require to refactor of `CircuitQNN` and similar classes inherited from `NeuralNetwork`.

**Comment by adekusar-drl** [comment]
Is the PR ready for review or something is still missing?

**Comment by IceKhan13** [comment]
> Is the PR ready for review or something is still missing?

Yes, quick fix is ready

**Comment by IceKhan13** [comment]
Hm, latest errors from linter came from main branch

https://github.com/Qiskit/qiskit-machine-learning/pull/188/checks?check_run_id=3400590479

and I cannot reproduce them on my local machine

Screen Shot 2021-08-23 at 11 53 13 AM

**Review by adekusar-drl — COMMENTED** [review]
Thanks a lot for taking care of the issue. As I understand from the tests, the problem arises when one tries to use `TorchConnector` without actual values bound to parameters? If so, could it be better to raise an exception with an explanation what happened?
Since this is a bug fix a reno file is required.

**Comment by IceKhan13** [comment]
> could it be better to raise an exception with an explanation what happened?

Do you mean non parametric inputs or weights is not a valid case at all? So, developers can not define CQNN without parametric inputs?

> Since this is a bug fix a reno file is required.

Added release note

**Review by adekusar-drl — APPROVED** [review]
Thanks for taking care of this issue. I think, it is a viable solution.

**Pull request merged**
