### PR TITLE
Replace sparse with sparse_output in the OneHotEncoder constructor

### PR DESCRIPTION
**Pull request by adekusar-drl**
### Summary
This PR replaces usage of `sparse` with `sparse_output` where `OneHotEncoder` is instantiated.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
We should update the requirements txt too, I imagine, as I see that change is effective from 1.2 but we allow older sklearn versions 

`scikit-learn>=0.20.0`

so given the change we now need 1.2 at a minimum it seems from sklearn:

> New in version 1.2: sparse was renamed to sparse_output
> Deprecated since version 1.2: sparse is deprecated in 1.2 and will be removed in 1.4. Use sparse_output instead.

**Comment by adekusar-drl** [comment]
Agree. Updated.

**Review by woodsp-ibm — APPROVED** [review]

**Comment by woodsp-ibm** [comment]
3.7 support in Qiskit ends with Terra 0.25 at end July. Place this on hold until such time as 3.7 support is removed from here commensurate with that?

**Comment by adekusar-drl** [comment]
On hold until we drop support of python 3.7

**Pull request merged**
