### PR TITLE
Fix forward pass computation cache

### LINKED ISSUE #204: AQGD does not return objective function values properly.
### Information

- **Qiskit Machine Learning version**: Tested on 0.3.0 and 0.2.1
- **Python version**: 3.7.9
- **Operating system**: OSX

### What is the current behaviour?
Returns the same value for all iterations. Graph produced by `callback_graph` in Tutorial 2 looks like this:
Screenshot 2021-09-05 at 18 00 50

### Steps to reproduce the problem
Change optimiser used in Tutorial 2 in docs for machine learning.

### What is the expected behaviour?
Changing values to be able to monitor convergence as intended. 

### Suggested solutions
No clue.

### PR DESCRIPTION
**Pull request by adekusar-drl**
### Summary
Objective functions cache result of forward computation. Initially this cache was based on the identifier (`a call of id()`) of the weights arraay. AQGD re-uses the same array for weights: it updates the values keeping an instance of the array the same. This caused to re-use the same forward pass value across all iteration. The forward pass cache now is based on actual values of weights.
Closes #204.

### CODE REVIEW

**Comment by adekusar-drl** [comment]
@woodsp-ibm Do we need a reno here? What do you think?

**Comment by woodsp-ibm** [comment]
It should have a reno when the bug affects end users.

**Comment by woodsp-ibm** [comment]
Should this be backported to stable - I don't know its severe enough to warrant a bug fix release just for this, but it can at least be backported ready I think.

**Comment by adekusar-drl** [comment]
Added reno, added backport label.

**Comment by adekusar-drl** [comment]
Seems like I messed up with the `stable backport potential` label and now the PR can't pass the CI.

**Comment by adekusar-drl** [comment]
@woodsp-ibm Could you please take a look? Seems all good now.

**Pull request merged**
