### PR TITLE
Fix hardcoded test size in breast cancer and digits dataset

### PR DESCRIPTION
**Pull request by bopardikarsoham**
As per Issue #371 , I've done the appropriate modifications.

### CODE REVIEW

**Comment by adekusar-drl** [comment]
Please take a look at my reply in the issue. This is wrong usage of the `test_size` parameter. 

Nevertheless, if you want to fix this, please take a look at the contributing guide here https://github.com/Qiskit/qiskit-machine-learning/blob/main/CONTRIBUTING.md and consider similar changes to other datasets.

**Comment by bopardikarsoham** [comment]
Yes, I just saw your response to the issue and saw where I was going wrong. Really sorry for the inconvenience.

**Comment by adekusar-drl** [comment]
> Yes, I just saw your response to the issue and saw where I was going wrong. Really sorry for the inconvenience.

@bopardikarsoham my apologies, you are right. In the `wine` and `iris` datasets the `test_size` is applied in the same way as you mentioned in the issue. So, the fix looks correct.

**Comment by bopardikarsoham** [comment]
I also had a query about why test_size is not set to 0.3 in datasets like wine and iris, as shown at https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/datasets/iris.py#L36.

**Comment by bopardikarsoham** [comment]
> > Yes, I just saw your response to the issue and saw where I was going wrong. Really sorry for the inconvenience.
> 
> @bopardikarsoham my apologies, you are right. In the `wine` and `iris` datasets the `test_size` is applied in the same way as you mentioned in the issue. So, the fix looks correct.

Yes, l saw that too. That's why I made the change.

**Comment by adekusar-drl** [comment]
> I also had a query about why test_size is not set to 0.3 in datasets like wine and iris, as shown at https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/datasets/iris.py#L36.

I'd say either `test_size` parameter should be set to `0.3` or to the passed `test_size` value everywhere.

**Comment by woodsp-ibm** [comment]
I am not sure if this is something we would want to do at this point. The dataset is initially split such that 0.3 of it is kept for test. Then out of the data that is split 0.7/0.3 ration,  training size and test_size amounts are taken. Maybe the ratio of 0.7 to 0.3 as per the dataset split is different than training_size/test_size split such that its not so great. Either way I think this will end up as breaking change and with the datasets being deprecated for removal I think it may be better to live with it. A user can directly use breast cancer etc if the behavior here does not work for them.

**Comment by adekusar-drl** [comment]
I close this PR as the datasets are deprecated.

**Pull request closed without merging**
