### PR TITLE
Fix tutorial to use UniformDistribution from qiskit-finance

### PR DESCRIPTION
**Pull request by manoelmarques**
### Summary
Terra `probability_distributions` has been deprecated for a while and has been removed from Terra: Qiskit/qiskit-terra#7562
Changed tutorial to use equivalent from qiskit-finance
Changed CI to install qiskit-finance

### Details and comments
The step to run stable tutorials against main code will fail. It has been disabled until this PR gets backported which needs to be done manually because mergify blocks when changes to CI are made.
It is ok to backport since qiskit-finance in Pypi contains the `probability_distributions`.

### CODE REVIEW

**Comment by adekusar-drl** [comment]
@manoelmarques I don't think we should introduce a dependency on finance here. I partially fixed this problem in #264, my bad, did not check the tutorials.

**Comment by manoelmarques** [comment]
Thanks @adekusar-drl . In this case could you please fix the 04 tutorial as well ? I will close this PR

**Comment by adekusar-drl** [comment]
> Thanks @adekusar-drl . In this case could you please fix the 04 tutorial as well ? I will close this PR

OK, will do.

**Comment by adekusar-drl** [comment]
May be `UniformDistribution` should have been moved to QML.

**Comment by manoelmarques** [comment]
Closing since the dependency on qiskit-finance will be removed from the tutorial

**Comment by adekusar-drl** [comment]
@manoelmarques See #299

**Pull request closed without merging**
