### PR TITLE
Switch to using black for code formatting

### PR DESCRIPTION
**Pull request by manoelmarques**
### Summary
Follows the changes made in Qiskit/qiskit-terra#6361

### CODE REVIEW

**Comment by adekusar-drl** [comment]
This is a disaster! I can't say we had a very well formatted code, but this is terrible.
instead of
```python
                    input_grad = grad_output.transpose(0, 1) @ input_grad.transpose(0, 1)
```
now:
```python
                    input_grad = grad_output.transpose(0, 1) @ input_grad.transpose(
                        0, 1
                    )
```

Or:
instead of
```python
                    weights_grad = weights_grad.to_dense()  # this should be eventually removed
```
it is
```python
                    weights_grad = (
                        weights_grad.to_dense()
                    )  # this should be eventually removed
```

Or:
```python
            parameterized_circuit = self._quantum_instance.transpile(parameterized_circuit)[0]
```
replaced with 
```python
            parameterized_circuit = self._quantum_instance.transpile(
                parameterized_circuit
            )[0]
```

and so on and so on...

**Comment by adekusar-drl** [comment]
Any ideas why `max-line-length=105`?

**Comment by manoelmarques** [comment]
Terra changed to 105 from 100 in their PR. I don't know why but would think it has to do on how black formatted code which may have added more lines.

**Review by woodsp-ibm — APPROVED** [review]

**Comment by woodsp-ibm** [comment]
This issue in Terra has a note as to the line length of 105 https://github.com/Qiskit/qiskit-terra/pull/5883

I agree it does not do a great job in some places - I made a comment in the equivalent PR in Nature.

**Comment by adekusar-drl** [comment]
Thanks for pointing out to the Nature's PR. I agree with @mtreinish in general. Well, of course we get rid of any formatting questions but at what a cost. 
I'd rather increase max line length to 140-150, we have wide screens for many years, and change the style.

**Comment by adekusar-drl** [comment]
> 
> 
> Terra changed to 105 from 100 in their PR. I don't know why but would think it has to do on how black formatted code which may have increased de size of the code in one line.

This is the answer from https://github.com/Qiskit/qiskit-terra/pull/5883:
> Black treats maximum-line-length "like a speed limit" ie if the least bad option is to exceed the line length by a little, then it will sometimes do so (I kept black using line length 100 and set the pylint/pycodestyle line length to 105 to accommodate this -- there are currently no places where this actually comes up in qiskit)

**Pull request merged**
